# Site settings
title: Harmony and Spencer | Wedding
email: webmaster@thesummitfw.com
description: > # this means to ignore newlines until "baseurl:"
 We're getting married!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://harmonyandspencer.com" # the base hostname & protocol for your site
images: "/images/"
encoding: utf-8
# Build settings
markdown: kramdown

sass:
    style: :compressed